update 5.19 kbuild patch
Signed-off-by: Peter Jung <admin@ptr1337.dev>

diff --git a/5.19/0007-kbuild-module.patch b/5.19/0007-kbuild-module.patch
--- a/5.19/0007-kbuild-module.patch
+++ b/5.19/0007-kbuild-module.patch
@@ -1,7 +1,7 @@
-From 6da25f28146e7603410e22e3c5b1a44d0f14448b Mon Sep 17 00:00:00 2001
+From 37fbaa67cdb1acc08fc783d599bf5d2dc1e99c3b Mon Sep 17 00:00:00 2001
 From: Peter Jung <admin@ptr1337.dev>
 Date: Mon, 18 Jul 2022 02:23:32 +0200
-Subject: [PATCH 07/15] kbuild-module
+Subject: [PATCH] kbuild-module
 
 Signed-off-by: Peter Jung <admin@ptr1337.dev>
 ---
@@ -32,15 +32,20 @@ Signed-off-by: Peter Jung <admin@ptr1337.dev>
  kernel/module/kallsyms.c                      |  41 ++-
  kernel/module/main.c                          |  43 ++-
  kernel/module/procfs.c                        |   2 +-
+ scripts/Kconfig.include                       |   2 +-
  scripts/Makefile.build                        |   5 +-
  scripts/Makefile.modinst                      |   3 +
  scripts/Makefile.package                      |   4 +-
  .../dummy-plugin-dir/include/plugin-version.h |   0
  scripts/dummy-tools/gcc                       |   8 +-
- scripts/mod/modpost.c                         |  24 +-
+ scripts/headers_install.sh                    |   2 -
+ scripts/kconfig/qconf-cfg.sh                  |   1 +
+ scripts/mod/file2alias.c                      |   4 +-
+ scripts/mod/modpost.c                         |  36 ++-
+ scripts/mod/modpost.h                         |   1 +
  scripts/module.lds.S                          |   2 +
  scripts/package/mkspec                        |   3 +
- 35 files changed, 415 insertions(+), 375 deletions(-)
+ 40 files changed, 424 insertions(+), 388 deletions(-)
  delete mode 100644 certs/blacklist_nohashes.c
  rename {scripts => certs}/check-blacklist-hashes.awk (100%)
  create mode 100644 kernel/module/Kconfig
@@ -1196,6 +1201,19 @@ index 1b6af54d88c1..80260fa4dac5 100644
  
  	seq_puts(m, "\n");
  	return 0;
+diff --git a/scripts/Kconfig.include b/scripts/Kconfig.include
+index 0496efd6e117..c1f4222d223d 100644
+--- a/scripts/Kconfig.include
++++ b/scripts/Kconfig.include
+@@ -25,7 +25,7 @@ failure = $(if-success,$(1),n,y)
+ 
+ # $(cc-option,<flag>)
+ # Return y if the compiler supports <flag>, n otherwise
+-cc-option = $(success,mkdir .tmp_$$$$; trap "rm -rf .tmp_$$$$" EXIT; $(CC) -Werror $(CLANG_FLAGS) $(1) -c -x c /dev/null -o .tmp_$$$$/tmp.o)
++cc-option = $(success,mkdir .tmp_$$; trap "rm -rf .tmp_$$" EXIT; $(CC) -Werror $(CLANG_FLAGS) $(1) -c -x c /dev/null -o .tmp_$$/tmp.o)
+ 
+ # $(ld-option,<flag>)
+ # Return y if the linker supports <flag>, n otherwise
 diff --git a/scripts/Makefile.build b/scripts/Makefile.build
 index cac070aee791..784f46d41959 100644
 --- a/scripts/Makefile.build
@@ -1270,11 +1288,72 @@ index b2483149bbe5..7db825843435 100755
  	exit 0
  fi
  
+diff --git a/scripts/headers_install.sh b/scripts/headers_install.sh
+index dd554bd436cc..4041881746ad 100755
+--- a/scripts/headers_install.sh
++++ b/scripts/headers_install.sh
+@@ -70,7 +70,6 @@ configs=$(sed -e '
+ #
+ # The format is <file-name>:<CONFIG-option> in each line.
+ config_leak_ignores="
+-arch/alpha/include/uapi/asm/setup.h:CONFIG_ALPHA_LEGACY_START_ADDRESS
+ arch/arc/include/uapi/asm/page.h:CONFIG_ARC_PAGE_SIZE_16K
+ arch/arc/include/uapi/asm/page.h:CONFIG_ARC_PAGE_SIZE_4K
+ arch/arc/include/uapi/asm/swab.h:CONFIG_ARC_HAS_SWAPE
+@@ -84,7 +83,6 @@ arch/nios2/include/uapi/asm/swab.h:CONFIG_NIOS2_CI_SWAB_SUPPORT
+ arch/x86/include/uapi/asm/auxvec.h:CONFIG_IA32_EMULATION
+ arch/x86/include/uapi/asm/auxvec.h:CONFIG_X86_64
+ arch/x86/include/uapi/asm/mman.h:CONFIG_X86_INTEL_MEMORY_PROTECTION_KEYS
+-include/uapi/asm-generic/fcntl.h:CONFIG_64BIT
+ include/uapi/linux/atmdev.h:CONFIG_COMPAT
+ include/uapi/linux/eventpoll.h:CONFIG_PM_SLEEP
+ include/uapi/linux/hw_breakpoint.h:CONFIG_HAVE_MIXED_BREAKPOINTS_REGS
+diff --git a/scripts/kconfig/qconf-cfg.sh b/scripts/kconfig/qconf-cfg.sh
+index 9b695e5cd9b3..ad652cb53947 100755
+--- a/scripts/kconfig/qconf-cfg.sh
++++ b/scripts/kconfig/qconf-cfg.sh
+@@ -20,5 +20,6 @@ fi
+ echo >&2 "*"
+ echo >&2 "* Could not find Qt5 via ${HOSTPKG_CONFIG}."
+ echo >&2 "* Please install Qt5 and make sure it's in PKG_CONFIG_PATH"
++echo >&2 "* You need $PKG"
+ echo >&2 "*"
+ exit 1
+diff --git a/scripts/mod/file2alias.c b/scripts/mod/file2alias.c
+index cbd6b0f48b4e..80d973144fde 100644
+--- a/scripts/mod/file2alias.c
++++ b/scripts/mod/file2alias.c
+@@ -1571,9 +1571,7 @@ void handle_moddevtable(struct module *mod, struct elf_info *info,
+ 		zeros = calloc(1, sym->st_size);
+ 		symval = zeros;
+ 	} else {
+-		symval = (void *)info->hdr
+-			+ info->sechdrs[get_secindex(info, sym)].sh_offset
+-			+ sym->st_value;
++		symval = sym_get_data(info, sym);
+ 	}
+ 
+ 	/* First handle the "special" cases */
 diff --git a/scripts/mod/modpost.c b/scripts/mod/modpost.c
-index 620dc8c4c814..7735d095338c 100644
+index 620dc8c4c814..26254e96c300 100644
 --- a/scripts/mod/modpost.c
 +++ b/scripts/mod/modpost.c
-@@ -339,8 +339,19 @@ static const char *sech_name(const struct elf_info *info, Elf_Shdr *sechdr)
+@@ -321,13 +321,10 @@ static void *sym_get_data_by_offset(const struct elf_info *info,
+ {
+ 	Elf_Shdr *sechdr = &info->sechdrs[secindex];
+ 
+-	if (info->hdr->e_type != ET_REL)
+-		offset -= sechdr->sh_addr;
+-
+ 	return (void *)info->hdr + sechdr->sh_offset + offset;
+ }
+ 
+-static void *sym_get_data(const struct elf_info *info, const Elf_Sym *sym)
++void *sym_get_data(const struct elf_info *info, const Elf_Sym *sym)
+ {
+ 	return sym_get_data_by_offset(info, get_secindex(info, sym),
+ 				      sym->st_value);
+@@ -339,8 +336,19 @@ static const char *sech_name(const struct elf_info *info, Elf_Shdr *sechdr)
  				      sechdr->sh_name);
  }
  
@@ -1295,7 +1374,18 @@ index 620dc8c4c814..7735d095338c 100644
  	return sech_name(info, &info->sechdrs[secindex]);
  }
  
-@@ -649,7 +660,7 @@ static void handle_symbol(struct module *mod, struct elf_info *info,
+@@ -466,6 +474,10 @@ static int parse_elf(struct elf_info *info, const char *filename)
+ 	sechdrs = (void *)hdr + hdr->e_shoff;
+ 	info->sechdrs = sechdrs;
+ 
++	/* modpost only works for relocatable objects */
++	if (hdr->e_type != ET_REL)
++		fatal("%s: not relocatable object.", filename);
++
+ 	/* Check if file offset is correct */
+ 	if (hdr->e_shoff > info->size) {
+ 		fatal("section header offset=%lu in file '%s' is bigger than filesize=%zu\n",
+@@ -649,7 +661,7 @@ static void handle_symbol(struct module *mod, struct elf_info *info,
  			const char *name, *secname;
  
  			name = symname + strlen("__ksymtab_");
@@ -1304,7 +1394,7 @@ index 620dc8c4c814..7735d095338c 100644
  
  			if (strstarts(secname, "___ksymtab_gpl+"))
  				sym_add_exported(name, mod, true);
-@@ -742,7 +753,6 @@ static const char *const section_white_list[] =
+@@ -742,7 +754,6 @@ static const char *const section_white_list[] =
  {
  	".comment*",
  	".debug*",
@@ -1312,7 +1402,7 @@ index 620dc8c4c814..7735d095338c 100644
  	".zdebug*",		/* Compressed debug sections. */
  	".GCC.command.line",	/* record-gcc-switches */
  	".mdebug*",        /* alpha, score, mips etc. */
-@@ -1217,7 +1227,7 @@ static Elf_Sym *find_elf_symbol2(struct elf_info *elf, Elf_Addr addr,
+@@ -1217,7 +1228,7 @@ static Elf_Sym *find_elf_symbol2(struct elf_info *elf, Elf_Addr addr,
  
  		if (is_shndx_special(sym->st_shndx))
  			continue;
@@ -1321,7 +1411,7 @@ index 620dc8c4c814..7735d095338c 100644
  		if (strcmp(symsec, sec) != 0)
  			continue;
  		if (!is_valid_name(elf, sym))
-@@ -1457,7 +1467,7 @@ static void default_mismatch_handler(const char *modname, struct elf_info *elf,
+@@ -1457,7 +1468,7 @@ static void default_mismatch_handler(const char *modname, struct elf_info *elf,
  	if (strstarts(fromsym, "reference___initcall"))
  		return;
  
@@ -1330,7 +1420,7 @@ index 620dc8c4c814..7735d095338c 100644
  	to = find_elf_symbol(elf, r->r_addend, sym);
  	tosym = sym_name(elf, to);
  
-@@ -1559,7 +1569,7 @@ static void extable_mismatch_handler(const char* modname, struct elf_info *elf,
+@@ -1559,7 +1570,7 @@ static void extable_mismatch_handler(const char* modname, struct elf_info *elf,
  				     Elf_Rela* r, Elf_Sym* sym,
  				     const char *fromsec)
  {
@@ -1339,7 +1429,7 @@ index 620dc8c4c814..7735d095338c 100644
  
  	sec_mismatch_count++;
  
-@@ -1593,7 +1603,7 @@ static void extable_mismatch_handler(const char* modname, struct elf_info *elf,
+@@ -1593,7 +1604,7 @@ static void extable_mismatch_handler(const char* modname, struct elf_info *elf,
  static void check_section_mismatch(const char *modname, struct elf_info *elf,
  				   Elf_Rela *r, Elf_Sym *sym, const char *fromsec)
  {
@@ -1348,6 +1438,28 @@ index 620dc8c4c814..7735d095338c 100644
  	const struct sectioncheck *mismatch = section_mismatch(fromsec, tosec);
  
  	if (mismatch) {
+@@ -1623,9 +1634,6 @@ static int addend_386_rel(struct elf_info *elf, Elf_Shdr *sechdr, Elf_Rela *r)
+ 		break;
+ 	case R_386_PC32:
+ 		r->r_addend = TO_NATIVE(*location) + 4;
+-		/* For CONFIG_RELOCATABLE=y */
+-		if (elf->hdr->e_type == ET_EXEC)
+-			r->r_addend += r->r_offset;
+ 		break;
+ 	}
+ 	return 0;
+diff --git a/scripts/mod/modpost.h b/scripts/mod/modpost.h
+index 044bdfb894b7..4d8a1ae1d1e3 100644
+--- a/scripts/mod/modpost.h
++++ b/scripts/mod/modpost.h
+@@ -187,6 +187,7 @@ void get_src_version(const char *modname, char sum[], unsigned sumlen);
+ /* from modpost.c */
+ char *read_text_file(const char *filename);
+ char *get_line(char **stringp);
++void *sym_get_data(const struct elf_info *info, const Elf_Sym *sym);
+ 
+ enum loglevel {
+ 	LOG_WARN,
 diff --git a/scripts/module.lds.S b/scripts/module.lds.S
 index 1d0e1e4dc3d2..3a3aa2354ed8 100644
 --- a/scripts/module.lds.S
