update dev patches
Signed-off-by: Peter Jung <admin@ptr1337.dev>

diff --git a/5.19/0010-kbuild-module.patch b/5.19/0010-kbuild-module.patch
--- a/5.19/0010-kbuild-module.patch
+++ b/5.19/0010-kbuild-module.patch
@@ -1,14 +1,15 @@
-From 76443bf94199d383ad94da36a231c9fda539a5f4 Mon Sep 17 00:00:00 2001
+From 3e2a5c17c90f6551c4524a4c604a3cd94d49a3f5 Mon Sep 17 00:00:00 2001
 From: Peter Jung <admin@ptr1337.dev>
 Date: Sun, 14 Aug 2022 11:11:23 +0200
-Subject: [PATCH 10/16] kbuild-module
+Subject: [PATCH 10/17] kbuild-module
 
 Signed-off-by: Peter Jung <admin@ptr1337.dev>
 ---
  .../admin-guide/kernel-parameters.txt         |  17 +-
  Documentation/kbuild/kconfig-language.rst     |   2 +-
  MAINTAINERS                                   |   2 +-
- Makefile                                      |  16 +-
+ Makefile                                      |  25 +-
+ arch/Kconfig                                  |  10 +
  certs/Makefile                                |  14 +-
  certs/blacklist_hashes.c                      |   1 -
  certs/blacklist_nohashes.c                    |   6 -
@@ -23,20 +24,22 @@ Signed-off-by: Peter Jung <admin@ptr1337.dev>
  scripts/Kconfig.include                       |   2 +-
  scripts/Makefile.build                        |   5 +-
  scripts/Makefile.compiler                     |   2 +-
+ scripts/Makefile.extrawarn                    |   1 -
  scripts/Makefile.lib                          |  13 +-
  scripts/Makefile.modinst                      |  10 +-
  scripts/Makefile.package                      |   4 +-
  scripts/checkstack.pl                         |   4 +
+ scripts/clang-tools/run-clang-tools.py        |   1 +
  .../dummy-plugin-dir/include/plugin-version.h |   0
- scripts/dummy-tools/gcc                       |   8 +-
+ scripts/dummy-tools/gcc                       |  10 +-
  scripts/headers_install.sh                    |   2 -
  scripts/kconfig/qconf-cfg.sh                  |   1 +
  scripts/mod/file2alias.c                      |   4 +-
- scripts/mod/modpost.c                         | 281 +++-------------
+ scripts/mod/modpost.c                         | 285 +++-------------
  scripts/mod/modpost.h                         |  33 +-
  scripts/module.lds.S                          |   2 +
  scripts/package/mkspec                        |   3 +
- 31 files changed, 540 insertions(+), 621 deletions(-)
+ 34 files changed, 557 insertions(+), 631 deletions(-)
  delete mode 100644 certs/blacklist_nohashes.c
  rename {scripts => certs}/check-blacklist-hashes.awk (100%)
  create mode 100644 kernel/module/Kconfig
@@ -111,7 +114,7 @@ index 3dff367799b3..90064315e306 100644
  MONOLITHIC POWER SYSTEM PMIC DRIVER
  M:	Saravanan Sekar <sravanhome@gmail.com>
 diff --git a/Makefile b/Makefile
-index e2edc38ce52c..8a8997efc09d 100644
+index e2edc38ce52c..6a44580afb24 100644
 --- a/Makefile
 +++ b/Makefile
 @@ -129,6 +129,9 @@ endif
@@ -124,7 +127,33 @@ index e2edc38ce52c..8a8997efc09d 100644
  # Remove trailing slashes
  ifneq ($(filter %/, $(KBUILD_EXTMOD)),)
  KBUILD_EXTMOD := $(shell dirname $(KBUILD_EXTMOD).)
-@@ -1375,16 +1378,21 @@ endif
+@@ -895,7 +898,8 @@ endif
+ ifdef CONFIG_LTO_CLANG
+ ifdef CONFIG_LTO_CLANG_THIN
+ CC_FLAGS_LTO	:= -flto=thin -fsplit-lto-unit
+-KBUILD_LDFLAGS	+= --thinlto-cache-dir=$(extmod_prefix).thinlto-cache
++export thinlto-dir = $(if $(CONFIG_LTO_CLANG_THIN_CACHEDIR),$(CONFIG_LTO_CLANG_THIN_CACHEDIR)/)
++KBUILD_LDFLAGS	+= --thinlto-cache-dir=$(thinlto-dir)$(extmod_prefix).thinlto-cache
+ else
+ CC_FLAGS_LTO	:= -flto
+ endif
+@@ -1112,13 +1116,11 @@ vmlinux-alldirs	:= $(sort $(vmlinux-dirs) Documentation \
+ 		     $(patsubst %/,%,$(filter %/, $(core-) \
+ 			$(drivers-) $(libs-))))
+ 
+-subdir-modorder := $(addsuffix modules.order,$(filter %/, \
+-			$(core-y) $(core-m) $(libs-y) $(libs-m) \
+-			$(drivers-y) $(drivers-m)))
+-
+ build-dirs	:= $(vmlinux-dirs)
+ clean-dirs	:= $(vmlinux-alldirs)
+ 
++subdir-modorder := $(addsuffix /modules.order, $(build-dirs))
++
+ # Externally visible symbols (used by link-vmlinux.sh)
+ KBUILD_VMLINUX_OBJS := $(head-y) $(patsubst %/,%/built-in.a, $(core-y))
+ KBUILD_VMLINUX_OBJS += $(addsuffix built-in.a, $(filter %/, $(libs-y)))
+@@ -1375,16 +1377,21 @@ endif
  
  ifneq ($(dtstree),)
  
@@ -150,6 +179,27 @@ index e2edc38ce52c..8a8997efc09d 100644
  ifneq ($(filter dtbs_check, $(MAKECMDGOALS)),)
  export CHECK_DTBS=y
  dtbs: dt_binding_check
+diff --git a/arch/Kconfig b/arch/Kconfig
+index 5ea3e3838c21..cc81de948950 100644
+--- a/arch/Kconfig
++++ b/arch/Kconfig
+@@ -731,6 +731,16 @@ config LTO_CLANG_THIN
+ 	    https://clang.llvm.org/docs/ThinLTO.html
+ 
+ 	  If unsure, say Y.
++
++config LTO_CLANG_THIN_CACHEDIR
++	string "Clang ThinLTO cache directory"
++	depends on LTO_CLANG_THIN
++	default ""
++	help
++	  This option allows users to choose a directory that stores
++	  Clang's ThinLTO cache.
++	  Leave empty for default.
++
+ endchoice
+ 
+ config ARCH_SUPPORTS_CFI_CLANG
 diff --git a/certs/Makefile b/certs/Makefile
 index 88a73b28d254..9486ed924731 100644
 --- a/certs/Makefile
@@ -1181,6 +1231,18 @@ index 86ecd2ac874c..94d0d40cddb3 100644
  	if ($(1)) >/dev/null 2>&1;	\
  	then echo "$(2)";		\
  	else echo "$(3)";		\
+diff --git a/scripts/Makefile.extrawarn b/scripts/Makefile.extrawarn
+index f5f0d6f09053..0621c39a3955 100644
+--- a/scripts/Makefile.extrawarn
++++ b/scripts/Makefile.extrawarn
+@@ -49,7 +49,6 @@ ifdef CONFIG_CC_IS_CLANG
+ KBUILD_CFLAGS += -Wno-initializer-overrides
+ KBUILD_CFLAGS += -Wno-format
+ KBUILD_CFLAGS += -Wno-sign-compare
+-KBUILD_CFLAGS += -Wno-format-zero-length
+ KBUILD_CFLAGS += $(call cc-disable-warning, pointer-to-enum-cast)
+ KBUILD_CFLAGS += -Wno-tautological-constant-out-of-range-compare
+ KBUILD_CFLAGS += $(call cc-disable-warning, unaligned-access)
 diff --git a/scripts/Makefile.lib b/scripts/Makefile.lib
 index 3fb6a99e78c4..f62770a0a84f 100644
 --- a/scripts/Makefile.lib
@@ -1283,13 +1345,34 @@ index d2c38584ece6..d48dfed6d3db 100755
  	} else {
  		print("wrong or unknown architecture \"$arch\"\n");
  		exit
+diff --git a/scripts/clang-tools/run-clang-tools.py b/scripts/clang-tools/run-clang-tools.py
+index f754415af398..1337cedca096 100755
+--- a/scripts/clang-tools/run-clang-tools.py
++++ b/scripts/clang-tools/run-clang-tools.py
+@@ -51,6 +51,7 @@ def run_analysis(entry):
+         checks += "linuxkernel-*"
+     else:
+         checks += "clang-analyzer-*"
++        checks += ",-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling"
+     p = subprocess.run(["clang-tidy", "-p", args.path, checks, entry["file"]],
+                        stdout=subprocess.PIPE,
+                        stderr=subprocess.STDOUT,
 diff --git a/scripts/dummy-tools/dummy-plugin-dir/include/plugin-version.h b/scripts/dummy-tools/dummy-plugin-dir/include/plugin-version.h
 new file mode 100644
 index 000000000000..e69de29bb2d1
 diff --git a/scripts/dummy-tools/gcc b/scripts/dummy-tools/gcc
-index b2483149bbe5..7db825843435 100755
+index b2483149bbe5..1db1889f6d81 100755
 --- a/scripts/dummy-tools/gcc
 +++ b/scripts/dummy-tools/gcc
+@@ -59,7 +59,7 @@ fi
+ if arg_contain -E "$@"; then
+ 	# For scripts/cc-version.sh; This emulates GCC 20.0.0
+ 	if arg_contain - "$@"; then
+-		sed -n '/^GCC/{s/__GNUC__/20/; s/__GNUC_MINOR__/0/; s/__GNUC_PATCHLEVEL__/0/; p;}'
++		sed -n '/^GCC/{s/__GNUC__/20/; s/__GNUC_MINOR__/0/; s/__GNUC_PATCHLEVEL__/0/; p;}; s/__LONG_DOUBLE_128__/1/ p'
+ 		exit 0
+ 	else
+ 		echo "no input files" >&2
 @@ -96,12 +96,8 @@ fi
  
  # To set GCC_PLUGINS
@@ -1352,7 +1435,7 @@ index cbd6b0f48b4e..80d973144fde 100644
  
  	/* First handle the "special" cases */
 diff --git a/scripts/mod/modpost.c b/scripts/mod/modpost.c
-index 620dc8c4c814..8484c0798f28 100644
+index 620dc8c4c814..22dc332eebfa 100644
 --- a/scripts/mod/modpost.c
 +++ b/scripts/mod/modpost.c
 @@ -321,13 +321,10 @@ static void *sym_get_data_by_offset(const struct elf_info *info,
@@ -1849,6 +1932,21 @@ index 620dc8c4c814..8484c0798f28 100644
  	/* if from section (name) is know good then skip it */
  	if (match(fromsec, section_white_list))
  		return;
+@@ -2203,13 +2018,11 @@ static void add_exported_symbols(struct buffer *buf, struct module *mod)
+ 	/* record CRCs for exported symbols */
+ 	buf_printf(buf, "\n");
+ 	list_for_each_entry(sym, &mod->exported_symbols, list) {
+-		if (!sym->crc_valid) {
++		if (!sym->crc_valid)
+ 			warn("EXPORT symbol \"%s\" [%s%s] version generation failed, symbol will not be versioned.\n"
+ 			     "Is \"%s\" prototyped in <asm/asm-prototypes.h>?\n",
+ 			     sym->name, mod->name, mod->is_vmlinux ? "" : ".ko",
+ 			     sym->name);
+-			continue;
+-		}
+ 
+ 		buf_printf(buf, "SYMBOL_CRC(%s, 0x%08x, \"%s\");\n",
+ 			   sym->name, sym->crc, sym->is_gpl_only ? "_gpl" : "");
 diff --git a/scripts/mod/modpost.h b/scripts/mod/modpost.h
 index 044bdfb894b7..1178f40a73f3 100644
 --- a/scripts/mod/modpost.h
